# Generated by Django 3.1.7 on 2021-04-07 07:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2021, 4, 7, 13, 1, 49, 895801)),
        ),
    ]
