# Generated by Django 3.1.7 on 2021-06-24 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
        migrations.RemoveField(
            model_name='student',
            name='username',
        ),
    ]
