# Generated by Django 3.1.7 on 2021-06-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_student_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='faculty',
            field=models.CharField(choices=[('Sft', 'Software'), ('Cmp', 'Computer')], max_length=15, null=True),
        ),
    ]
