# Generated by Django 3.1.7 on 2021-07-15 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210627_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='reserved_books',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='total_books_due',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
