# Generated by Django 3.1.7 on 2021-06-22 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0002_shelf_total_number_of_books'),
        ('books', '0002_borrower_fine_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='available_copies',
        ),
        migrations.RemoveField(
            model_name='book',
            name='total_copies',
        ),
        migrations.AlterField(
            model_name='book',
            name='shelf',
            field=models.ManyToManyField(related_name='shelf', through='books.Register', to='shelf.Shelf'),
        ),
    ]
