# Generated by Django 3.1.7 on 2021-06-22 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0002_shelf_total_number_of_books'),
        ('books', '0003_auto_20210622_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='shelf',
            field=models.ManyToManyField(null=True, related_name='shelf', through='books.Register', to='shelf.Shelf'),
        ),
    ]
