# Generated by Django 3.1.7 on 2021-07-11 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_borrower_issued_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='fine',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.book'),
        ),
        migrations.AddField(
            model_name='fine',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
