# Generated by Django 3.1.7 on 2021-07-11 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20210711_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fine',
            name='book',
        ),
        migrations.RemoveField(
            model_name='fine',
            name='student',
        ),
        migrations.AddField(
            model_name='fine',
            name='borrower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.borrower'),
        ),
    ]
