# Generated by Django 3.1.7 on 2021-07-11 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210627_1355'),
        ('books', '0008_auto_20210711_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fine',
            name='borrower',
        ),
        migrations.AddField(
            model_name='borrower',
            name='is_deposited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fine',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.book'),
        ),
        migrations.AddField(
            model_name='fine',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.student'),
        ),
    ]
