# Generated by Django 3.1.7 on 2021-07-13 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0003_remove_shelf_shelf_capacity'),
        ('books', '0009_auto_20210711_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.book'),
        ),
        migrations.AlterField(
            model_name='register',
            name='shelf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shelf.shelf'),
        ),
    ]
