# Generated by Django 3.1.7 on 2021-07-17 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0003_remove_shelf_shelf_capacity'),
        ('books', '0010_auto_20210713_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='shelf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shelf.shelf'),
        ),
    ]
