# Generated by Django 3.1.7 on 2021-06-19 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelf',
            name='total_number_of_books',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
