# Generated by Django 3.1.7 on 2021-06-27 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0002_shelf_total_number_of_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelf',
            name='shelf_capacity',
        ),
    ]
